### ISSUE TITLE
Unable to build native with quarkus-opensearch dependency

### ISSUE THREAD

**Issue by bechhansen** [quarkiverse/quarkus-opensearch#211]
Hi

I'm unable to build a native Quarkus application when I have added the quarkus-opensearch dependency to the pom.xml file.
I have reproduced the issue on a simple project as described in https://quarkus.io/guides/getting-started.

I have reproduced the issue on Windows and on Ubuntu Linux.
I have reproduced the issue on Quarkus 3.7.4 and 3.8.2.

I create the project by calling: 
`mvn io.quarkus.platform:quarkus-maven-plugin:3.8.2:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=getting-started \
    -Dextensions='resteasy-reactive'`

I'm able to do a native build on the new project by calling: `./mvnw package -e -DskipTests -Pnative -Dquarkus.native.container-build=true`

After adding the maven dependency I'm not able to a native build. I get the following error:
`[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.7.4:build (default) on project getting-started: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure:Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: io.quarkus.deployment.pkg.steps.NativeImageBuildStep$ImageGenerationFailureException: Image generation failed. Exit code: 1
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:468)
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:258)
[ERROR]         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:1583)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.7.4:build (default) on project getting-started: Failed to build quarkus application`

I have attached the project that reproduces the issue and the full build output.
[getting-started.zip](https://github.com/quarkiverse/quarkus-opensearch/files/14607426/getting-started.zip)
[Output.txt](https://github.com/quarkiverse/quarkus-opensearch/files/14607430/Output.txt)

**Comment by sboeckelmann** [comment]
@bechhansen 
was fixed with Version >=1.6.4

**Comment by bechhansen** [comment]
> @bechhansen was fixed with Version >=1.6.4

@sboeckelmann
Excellent news. We have just tried to compile and it looks like it was successful. Thanks a million!
